/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import physiotherapy.DBConnection;
import physiotherapy.MonthlyPatient;

/**
 *
 * @author 94712
 */
public class MonthlyPatientUI extends javax.swing.JFrame {

    /**
     * Creates new form MonthlyPatient
     */
    public MonthlyPatientUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGetDetails = new javax.swing.JButton();
        txtTo = new javax.swing.JTextField();
        txtFrom = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Monthly Patient");

        jLabel2.setText("From:");

        jLabel3.setText("To:");

        btnGetDetails.setBackground(new java.awt.Color(0, 153, 153));
        btnGetDetails.setText("Get Patient Details");
        btnGetDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDetailsActionPerformed(evt);
            }
        });

        btnBack.setText("Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(240, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)))
                .addGap(198, 198, 198))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(btnGetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addComponent(btnGetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDetailsActionPerformed
        // TODO add your handling code here:
        
        
        
        //choose location to save
        
//        JFileChooser exelFileChooser = new JFileChooser("D:\\exelFiles");
//        exelFileChooser.setDialogTitle("Save As");
//        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXXCEL FILES", "xls","xlsx","xlsm");
//        exelFileChooser.setFileFilter(fnef);
//        int excelCooser = exelFileChooser.showSaveDialog(null);
//        
//        if(excelCooser == JFileChooser.APPROVE_OPTION ){
//        
//            XSSFWorkbook excelJTableExporter = new XSSFWorkbook();
//            XSSFSheet excelSheet = excelJTableExporter.createSheet("JTable Sheet");
//            
//            for(int i=0;i<11;i++){
//                XSSFRow excelRow = excelSheet.createRow(i);
//                for(int j=0;j<10;j++){
//                    XSSFCell excellCell = excelRow.createCell(j);
//                }
//            }
//        }
        
        
        
        
        
        
        
        
        
        try{
//            Date Fromdate = dateChooserComboFrom.getDateFormat();
//            Date Todate = dateChooserComboTo.getText();
            String Fromdate = txtFrom.getText();
            String Todate = txtTo.getText();
//            
//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
//            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");

//            String Fromdate = dateChooserComboFrom.getText().replaceAll("/", "-");
//            String Todate = dateChooserComboTo.getText().replaceAll("/", "-");
//            System.out.println(""+Fromdate);
     

//            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
////            System.out.println(dateFormat.format(new Date()));
//                Date date = dateFormat.parse(Fromdate);
//                System.out.println(""+date);
//            Date fromDate = dateChooserComboFrom.getDateFormat();


//Date d = sdf.parse(dateChooserComboFrom.getText());
//String d2 = sdf2.format(d);
//System.out.println(d2);
        





//            System.out.println(""+formattedFromDate);
            
            
            //to stop sql injection
                PreparedStatement pst=null;
                ResultSet rs = null;
            
                
            
            Connection conn = DBConnection.connect();
            
//            String sql = "select * from patient where (date between "+ Fromdate+ "And"+Todate )";
//            int Fdate = Integer.parseInt(Fromdate);
//            int Tdate = Integer.parseInt(Todate);
            String sql = "SELECT * FROM `patient` WHERE `date` BETWEEN '" +Fromdate+"' AND '"+Todate+"'";
            
            
            
           
            
            
                pst = conn.prepareStatement(sql);               
                rs = pst.executeQuery();
                
                String name = "";
                String age ="" ;
                String gender = "";
                String addrss="";
                String Occu="";
                String Contct ="";
                String email="";
                String admit="";
                String ward ="";
                String date = "";
                
                String completeReport = "";
               
            while(rs.next()){
                 System.out.println("ssdsds");
                    name = rs.getString("Name");
                    age = rs.getString("Age");
                    gender = rs.getString("Gender");
                    addrss = rs.getString("Address");
                    Occu = rs.getString("Occupation");
                    Contct = rs.getString("Contact_number");
                    email = rs.getString("email");
                    admit = rs.getString("admit");
                    ward = rs.getString("ward");
                    date = rs.getString("date");
                    
//                    System.out.println(""+rs.next());
                    String v = name+","+age+","+gender+","+addrss+","+Occu+","+Contct+","+email+","+admit+","+ward+","+date+"\n";
                    completeReport += v;
                }
             MonthlyPatient.WriteCSV(completeReport);
            
            System.out.println("Finished");
            
            
//            for(int j=0;j<11;j++){
//                for(int i = Fdate;i<=Tdate;i++){
//                    
//                }
//            }
            
            
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_btnGetDetailsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ViewPatient v= new ViewPatient();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlyPatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlyPatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlyPatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlyPatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlyPatientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGetDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
